[package]
name = "coloring-book"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
tera = "1.19.1"
thiserror = "1.0.56"

[dev-dependencies]
anyhow = "1.0.79"
